#!/bin/bash

# declaring modules function
clean () {
  apt-get clean
}

install_essential () {
  apt install python3-configobj python3-pil  python3-serial  python3-usb python3-pip
}

install_weewx_dependency () {
   sudo_check 
   apt install python3-cheetah
   apt install 

}

download_weewx () {
  echo "Downloading weewx file" 
  wget -o weex-4.10.2 https://weewx.com/downloads/weewx-4.10.2.tar.gz
  [ "$?" = 1 ] && echo "Failed to download weewx"  & exit 1
}

wifi_check () {
  # check if wifi connection is available
  ping -q -c1 google.com &>/dev/null && echo online || echo offline
}

install_wifi_private () {
  echo >>
  network={
         ssid="eduroam"
         scan_ssid=1
         key_mgmt=WPA-EAP
         eap=PEAP
         identity="*****@*****.edu"
         anonymous_identity="*****@*****.edu"
         password="*****"
         ca_cert="/usr/share/ca-certificates/eduroam.pem"
         phase1="peaplabel=auto peapver=auto"
         phase2="auth=MSCHAPV2"
       }
  <
  wpa_cli -i wlan0 reconfigure
}


install_weewix () {
  apt-get update
  apt-get install weewx
}

install_database () {
  # Required if you are using MySQL (MariaDB):
  apt install mariadb-client python3-mysqldb
}
install_iot () {

}

install_mqtt () {
  
}

## Main ## 

main () {
  while [ -n "$1" ]
  do
     case "$1" in
	 ;;
       --install-dependency )
	 install_dependency
	 shift
	 ;;
       --version | -v)
	 echo '1.0'
	 ;;
              * | -*)
	 echo 'Invalid argument'
	 help
	 exit 1
	 break
	 ;;
     esac
  done
}

help () {
  echo "Usuage: $(basename $0) <--con|--dis|-a|-ac>. First, edit the variable to match your bluetooth interface MAC  address. "
  echo ''
  echo 'Where:'
  echo '  -r,--restart          restart the bluetooth headset connection'
  echo '  -l,--list             show current bluetooth devices'
  echo '  --dis,--disconnect       disconnect bluetooth headset'
  echo '  -a,--audio            connect with audio only'
  echo '  -ac,--audio-mic       connect with both audio and mic'
  echo '  -m,--mute	        mute the audio'
  echo '  -um,--unmute	        unmute the audio'
  echo '  -i,--install	        install dependency'

  echo ''
  echo 'Example:'
  echo "  $(basename $0) -c | --check   Check if the device is connected"
}

main "$@"
