#!/bin/bash

# declaring modules function
clean () {
  apt-get clean
}

wifi_check () {
  # check if wifi connection is available
}

install_wifi_private () {
  echo >>
  network={
         ssid="eduroam"
         scan_ssid=1
         key_mgmt=WPA-EAP
         eap=PEAP
         identity="*****@*****.edu"
         anonymous_identity="*****@*****.edu"
         password="*****"
         ca_cert="/usr/share/ca-certificates/eduroam.pem"
         phase1="peaplabel=auto peapver=auto"
         phase2="auth=MSCHAPV2"
       }
  <
  wpa_cli -i wlan0 reconfigure
}


install_weewix () {
  apt-get update
  apt-get install weewx
}

install_iot () {

}

install_mqtt () {
  
}

## Main ## 
case $1 in 
  weewix)
    install_weewix
